"""empty message

Revision ID: 313232ca1f76
Revises: a7792c5e306e
Create Date: 2019-10-10 15:43:20.818428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313232ca1f76'
down_revision = 'a7792c5e306e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('checkpoints_tgs_id_fkey', 'checkpoints', type_='foreignkey')
    op.drop_column('checkpoints', 'tgs_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkpoints', sa.Column('tgs_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('checkpoints_tgs_id_fkey', 'checkpoints', 'tgs', ['tgs_id'], ['id'])
    # ### end Alembic commands ###
