"""empty message

Revision ID: 446eef90bb25
Revises: e1622956318d
Create Date: 2019-10-08 11:10:55.205463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446eef90bb25'
down_revision = 'e1622956318d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkpoints', sa.Column('subject_name', sa.String(length=128), nullable=False))
    op.create_foreign_key(None, 'checkpoints', 'subjects', ['subject_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checkpoints', type_='foreignkey')
    op.drop_column('checkpoints', 'subject_name')
    # ### end Alembic commands ###
