"""empty message

Revision ID: a7792c5e306e
Revises: 446eef90bb25
Create Date: 2019-10-08 12:51:03.004103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7792c5e306e'
down_revision = '446eef90bb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkpoints_fields', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    op.add_column('checkpoints_fields', sa.Column('type', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkpoints_fields', 'type')
    op.drop_column('checkpoints_fields', 'is_hidden')
    # ### end Alembic commands ###
