"""empty message

Revision ID: e1622956318d
Revises: d293b0801bcc
Create Date: 2019-10-08 10:57:43.761654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1622956318d'
down_revision = 'd293b0801bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('res', sa.String(length=40), nullable=True))
    op.drop_column('progress', 'passed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('progress', 'res')
    # ### end Alembic commands ###
